// Gamer profiles for CarryMe
export const PROFILES = [
  {
    id: "aura_jett",
    tag: "Aura_Jett",
    age: 21,
    level: 78,
    location: "Chicago, IL",
    avatar: "☄️",
    image: "assets/aura_jett.jpg",
    platforms: ["PC"],
    categories: ["FPS", "Competitive"],
    games: ["Valorant", "Counter-Strike 2"],
    playstyle: "Competitive",
    roles: ["Duelist", "Entry Frag"],
    bio: "If you don't buy me Vandal round 2, I'm throwing. 😤 Valorant Diamond 3. Peak immortal. Carry me or get carried, no in-betweens.",
    intro: "Need a pocket healer or are you just going to block my line of sight?",
    color: "#ff007f"
  },
  {
    id: "cozy_cat",
    tag: "CozyCat",
    age: 23,
    level: 42,
    location: "Seattle, WA",
    avatar: "🐱",
    image: "assets/cozy_cat.jpg",
    platforms: ["Switch"],
    categories: ["Cozy", "Simulation"],
    games: ["Animal Crossing: New Horizons", "Stardew Valley", "Minecraft"],
    playstyle: "Casual",
    roles: ["Builder", "Gatherer"],
    bio: "Looking for someone to share coffee at Brewster's and water my pumpkins. Stardew year 4. ☕ Let's build a blue chicken army together!",
    intro: "Hello! 🐾 Can I show you my island's layout, or are you too busy running wagers?",
    color: "#00ffcc"
  },
  {
    id: "elden_slayer",
    tag: "EldenSlayer",
    age: 26,
    level: 195,
    location: "Austin, TX",
    avatar: "⚔️",
    image: "assets/elden_slayer.jpg",
    platforms: ["PC", "PlayStation"],
    categories: ["Soulslike", "RPG"],
    games: ["Elden Ring", "Dark Souls III", "Lies of P"],
    playstyle: "Completionist",
    roles: ["Melee DPS", "Solo Boss Runner"],
    bio: "Defeated Malenia solo with a dance pad. Lore enthusiast. If you think spirit ashes are mandatory, we can still be friends... maybe.",
    intro: "Tarnished, have you braved the Land of Shadow, or do you hide behind NPC summons?",
    color: "#ffd700"
  },
  {
    id: "support_bae",
    tag: "SupportBae",
    age: 22,
    level: 54,
    location: "Boston, MA",
    avatar: "💖",
    platforms: ["PC"],
    categories: ["MOBA", "Hero Shooter"],
    games: ["Overwatch 2", "League of Legends"],
    playstyle: "Casual",
    roles: ["Support", "Healer"],
    bio: "Mercy/Yuumi main looking for a pocket DPS to carry me out of Silver. 🥺 I will pocket you, damage boost you, and never let you die!",
    intro: "Need a dedicated pocket healer to keep your K/DA looking beautiful?",
    color: "#ff66cc"
  },
  {
    id: "retro_pixel",
    tag: "RetroPixel",
    age: 29,
    level: 99,
    location: "Denver, CO",
    avatar: "🕹️",
    platforms: ["Switch"],
    categories: ["Retro", "Indie", "Platformers"],
    games: ["Celeste", "Hollow Knight", "Super Mario World"],
    playstyle: "Achievements",
    roles: ["Speedrunner"],
    bio: "Collector of old arcade cabinets and CRT monitors. Celeste B-sides are my therapy. Let's debate whether Super Metroid is the best game ever.",
    intro: "Hey! Do you appreciate pixel art and tight platformer physics, or are you purely 3D?",
    color: "#ff9900"
  },
  {
    id: "nuke_tactics",
    tag: "NukeTactics",
    age: 27,
    level: 150,
    location: "Atlanta, GA",
    avatar: "🎖️",
    platforms: ["Xbox", "PlayStation"],
    categories: ["FPS", "Tactical"],
    games: ["Call of Duty: Warzone", "Apex Legends"],
    playstyle: "Competitive",
    roles: ["IGL (In-Game Leader)", "Sniper"],
    bio: "Ranked Warzone sweat. Call outs only. Let's land Superstore, secure the loadout, and get this win. Have mic, will travel.",
    intro: "LFG. Need a solid co-pilot who actually listens to pings and shares plates.",
    color: "#00ff66"
  },
  {
    id: "mana_shield",
    tag: "ManaShield",
    age: 31,
    level: 80,
    location: "New York, NY",
    avatar: "🛡️",
    platforms: ["PC"],
    categories: ["MMORPG"],
    games: ["World of Warcraft", "Final Fantasy XIV"],
    playstyle: "Achievements",
    roles: ["Tank", "Guild Leader"],
    bio: "Mythic Raider & Progression Tank. FFXIV Savage clear. I spend my weekends reading logs and organizing spreadsheets. I'll pull agro for you.",
    intro: "Hey there! Ready to run some high-level dungeons, or do you stand in the fire?",
    color: "#8e44ad"
  },
  {
    id: "faker_fanboy",
    tag: "FakerFanboy",
    age: 20,
    level: 65,
    location: "Los Angeles, CA",
    avatar: "⚡",
    platforms: ["PC"],
    categories: ["MOBA", "Competitive"],
    games: ["League of Legends", "Teamfight Tactics"],
    playstyle: "Competitive",
    roles: ["Mid Laner", "Shotcaller"],
    bio: "Challenger in my dreams, Gold II in reality. LoL Esports is life. T1 fighting! Let's watch Worlds and argue over draft picks.",
    intro: "What's your main role? If you say Jungle, please promise you'll gank mid.",
    color: "#e74c3c"
  },
  {
    id: "loot_goblin",
    tag: "LootGoblin",
    age: 25,
    level: 100,
    location: "Miami, FL",
    avatar: "💰",
    platforms: ["PC", "PlayStation"],
    categories: ["ARPG", "Looters"],
    games: ["Diablo IV", "Path of Exile"],
    playstyle: "Completionist",
    roles: ["DPS", "Min-Maxer"],
    bio: "Min-maxing build guides is my love language. If it glows, it goes in my inventory. Looking for a duo to grind nightmare dungeons with.",
    intro: "My build has 400% critical strike damage. Want to watch me melt some world bosses?",
    color: "#f1c40f"
  },
  {
    id: "diamond_steve",
    tag: "DiamondSteve",
    age: 24,
    level: 30,
    location: "Portland, OR",
    avatar: "🧱",
    platforms: ["PC", "Switch"],
    categories: ["Sandbox", "Casual"],
    games: ["Minecraft", "Terraria"],
    playstyle: "Casual",
    roles: ["Builder", "Redstone Engineer"],
    bio: "I build massive redstone contraptions that server admins hate. Survival mode enthusiast. Let's make a house together with matching beds.",
    intro: "Hey! Do you want to build a base, or are you just here to mine my diamonds?",
    color: "#3498db"
  },
  {
    id: "hadestown",
    tag: "Hadestown",
    age: 22,
    level: 85,
    location: "Philadelphia, PA",
    avatar: "🔥",
    platforms: ["PC", "Switch"],
    categories: ["Roguelike", "Indie"],
    games: ["Hades II", "Dead Cells", "Slay the Spire"],
    playstyle: "Achievements",
    roles: ["Speedrunner"],
    bio: "Melinoë is my queen. Speedrunning heat 32 runs in Hades. Let's talk Greek mythology and argue over which God boon is best.",
    intro: "Death to Chronos. Do you think you can escape my swipe deck?",
    color: "#e67e22"
  },
  {
    id: "wavedash",
    tag: "Wavedash",
    age: 28,
    level: 110,
    location: "Phoenix, AZ",
    avatar: "👊",
    platforms: ["PlayStation", "Xbox"],
    categories: ["Fighting"],
    games: ["Street Fighter 6", "Tekken 8", "Guilty Gear -Strive-"],
    playstyle: "Competitive",
    roles: ["Rushdown", "Frame Data Analyst"],
    bio: "Tekken God Rank. Frame data analyst. If you can't break throws, don't match. Just kidding! I'll teach you how to perfect parry in SF6.",
    intro: "1v1 me, local play. If you win, you get to choose where we eat. Deal?",
    color: "#95a5a6"
  },
  {
    id: "sims_queen",
    tag: "SimsQueen",
    age: 23,
    level: 25,
    location: "San Francisco, CA",
    avatar: "💎",
    platforms: ["PC"],
    categories: ["Simulation", "Casual"],
    games: ["The Sims 4", "Cities: Skylines"],
    playstyle: "Casual",
    roles: ["Storyteller", "Builder"],
    bio: "I write 10-generation family legacies. 😭 My builds take 12 hours. Looking for someone who doesn't mind me talking about Sim dramas.",
    intro: "Sul sul! 👋 If we were Sims, I'd definitely put a heart eyes bubble over my head.",
    color: "#16a085"
  },
  {
    id: "starfield_voyager",
    tag: "StarfieldVoyager",
    age: 30,
    level: 70,
    location: "Salt Lake City, UT",
    avatar: "🚀",
    platforms: ["PC", "Xbox"],
    categories: ["Sci-Fi", "RPG"],
    games: ["Starfield", "Mass Effect Legendary Edition", "No Man's Sky"],
    playstyle: "Lore",
    roles: ["Explorer", "Pilot"],
    bio: "Garrus Vakarian is the standard. Space explorer, ship builder, star gazer. Let's build a custom outpost on an exotic planet.",
    intro: "I've scanned 100 planets, but I've never seen anyone quite like you. 🌌",
    color: "#2c3e50"
  },
  {
    id: "raid_boss",
    tag: "RaidBoss",
    age: 28,
    level: 180,
    location: "Detroit, MI",
    avatar: "👑",
    platforms: ["PC", "Xbox"],
    categories: ["Shooter", "MMORPG"],
    games: ["Destiny 2", "World of Warcraft"],
    playstyle: "Achievements",
    roles: ["Shotcaller", "DPS"],
    bio: "Destiny 2 Raid Sherpa. I have clear counts in the hundreds. I will explain the mechanics, keep the team alive, and make sure we get the loot.",
    intro: "Need a Sherpa for the raid, or are you ready to carry me instead?",
    color: "#d35400"
  }
];
